/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Allegato model module.
 * @module model/Allegato
 * @version 2.0.0
 */
export default class Allegato {
  /**
   * Constructs a new <code>Allegato</code>.
   * @alias module:model/Allegato
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Allegato</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Allegato} obj Optional instance to populate.
   * @return {module:model/Allegato} The populated <code>Allegato</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Allegato();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('dimensione'))
        obj.dimensione = ApiClient.convertToType(data['dimensione'], 'Number');
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
Allegato.prototype.nome = undefined;

/**
 * @member {Number} dimensione
 */
Allegato.prototype.dimensione = undefined;

/**
 * @member {String} file
 */
Allegato.prototype.file = undefined;

