/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CallbackData model module.
 * @module model/CallbackData
 * @version 2.0.0
 */
export default class CallbackData {
  /**
   * Constructs a new <code>CallbackData</code>.
   * @alias module:model/CallbackData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CallbackData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CallbackData} obj Optional instance to populate.
   * @return {module:model/CallbackData} The populated <code>CallbackData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CallbackData();
      if (data.hasOwnProperty('method'))
        obj.method = ApiClient.convertToType(data['method'], 'String');
      if (data.hasOwnProperty('field'))
        obj.field = ApiClient.convertToType(data['field'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>method</code> property.
 * @enum {String}
 * @readonly
 */
CallbackData.MethodEnum = {
  /**
   * value: "JSON"
   * @const
   */
  JSON: "JSON",

  /**
   * value: "POST"
   * @const
   */
  POST: "POST"
};
/**
 * Indicare il metodo con cui si vogliono ricevere i dati con il callback, per impostazione predefinita è POST
 * @member {module:model/CallbackData.MethodEnum} method
 */
CallbackData.prototype.method = undefined;

/**
 * Nome del campo contenente i dati di ritorno della callback
 * @member {String} field
 */
CallbackData.prototype.field = undefined;

/**
 * Url dove verrà effettuata la chiamata di callback
 * @member {String} url
 */
CallbackData.prototype.url = undefined;

/**
 * Oggetto da completare a proprio piacimento con dati aggiuntivi che possono essere riutilizzati con il callback
 * @member {Object} data
 */
CallbackData.prototype.data = undefined;

