/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Dollaro model module.
 * @module model/Dollaro
 * @version 2.0.0
 */
export default class Dollaro {
  /**
   * Constructs a new <code>Dollaro</code>.
   * @alias module:model/Dollaro
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Dollaro</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dollaro} obj Optional instance to populate.
   * @return {module:model/Dollaro} The populated <code>Dollaro</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Dollaro();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('tipo'))
        obj.tipo = ApiClient.convertToType(data['tipo'], 'String');
      if (data.hasOwnProperty('opzioni'))
        obj.opzioni = ApiClient.convertToType(data['opzioni'], 'String');
      if (data.hasOwnProperty('ordine'))
        obj.ordine = ApiClient.convertToType(data['ordine'], 'String');
      if (data.hasOwnProperty('istruzioni'))
        obj.istruzioni = ApiClient.convertToType(data['istruzioni'], 'String');
      if (data.hasOwnProperty('null'))
        obj._null = ApiClient.convertToType(data['null'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
Dollaro.prototype.nome = undefined;

/**
 * @member {String} tipo
 */
Dollaro.prototype.tipo = undefined;

/**
 * @member {String} opzioni
 */
Dollaro.prototype.opzioni = undefined;

/**
 * @member {String} ordine
 */
Dollaro.prototype.ordine = undefined;

/**
 * @member {String} istruzioni
 */
Dollaro.prototype.istruzioni = undefined;

/**
 * @member {Boolean} _null
 */
Dollaro.prototype._null = undefined;

