/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Esito model module.
 * @module model/Esito
 * @version 2.0.0
 */
export default class Esito {
  /**
   * Constructs a new <code>Esito</code>.
   * @alias module:model/Esito
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Esito</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Esito} obj Optional instance to populate.
   * @return {module:model/Esito} The populated <code>Esito</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Esito();
      if (data.hasOwnProperty('info'))
        obj.info = ApiClient.convertToType(data['info'], 'String');
      if (data.hasOwnProperty('codice'))
        obj.codice = ApiClient.convertToType(data['codice'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} info
 */
Esito.prototype.info = undefined;

/**
 * @member {String} codice
 */
Esito.prototype.codice = undefined;

