/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Campo from './Campo';

/**
 * The JsonStruttura model module.
 * @module model/JsonStruttura
 * @version 2.0.0
 */
export default class JsonStruttura {
  /**
   * Constructs a new <code>JsonStruttura</code>.
   * @alias module:model/JsonStruttura
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JsonStruttura</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JsonStruttura} obj Optional instance to populate.
   * @return {module:model/JsonStruttura} The populated <code>JsonStruttura</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JsonStruttura();
      if (data.hasOwnProperty('campi'))
        obj.campi = Campo.constructFromObject(data['campi']);
      if (data.hasOwnProperty('validazione'))
        obj.validazione = ApiClient.convertToType(data['validazione'], 'String');
      if (data.hasOwnProperty('istruzioni'))
        obj.istruzioni = ApiClient.convertToType(data['istruzioni'], 'String');
      if (data.hasOwnProperty('istruzioni_ricerca'))
        obj.istruzioniRicerca = ApiClient.convertToType(data['istruzioni_ricerca'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Campo} campi
 */
JsonStruttura.prototype.campi = undefined;

/**
 * @member {String} validazione
 */
JsonStruttura.prototype.validazione = undefined;

/**
 * @member {String} istruzioni
 */
JsonStruttura.prototype.istruzioni = undefined;

/**
 * @member {String} istruzioniRicerca
 */
JsonStruttura.prototype.istruzioniRicerca = undefined;

