/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The JsonVisura model module.
 * @module model/JsonVisura
 * @version 2.0.0
 */
export default class JsonVisura {
  /**
   * Constructs a new <code>JsonVisura</code>.
   * Oggetto per passare tutti i campi di input richiesti per generare un documento di output dal servizio richiesto. Se si deve passare un file, deve essere passato in questo modo: name + &#x27;|data:&#x27; + tipo di file + &#x27;;base64,&#x27; + base64_encode(contenuto del file); esempio: &#x27;$2&#x27; : &#x27;test_file|data:image/png;base64,abcdefghijklmnopqrstuvwxyz0123456789&#x27;
   * @alias module:model/JsonVisura
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JsonVisura</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JsonVisura} obj Optional instance to populate.
   * @return {module:model/JsonVisura} The populated <code>JsonVisura</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JsonVisura();
      if (data.hasOwnProperty('$0'))
        obj._0 = ApiClient.convertToType(data['$0'], 'String');
      if (data.hasOwnProperty('$n'))
        obj.n = ApiClient.convertToType(data['$n'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _0
 */
JsonVisura.prototype._0 = undefined;

/**
 * @member {String} n
 */
JsonVisura.prototype.n = undefined;

