/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Opzione model module.
 * @module model/Opzione
 * @version 2.0.0
 */
export default class Opzione {
  /**
   * Constructs a new <code>Opzione</code>.
   * @alias module:model/Opzione
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Opzione</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Opzione} obj Optional instance to populate.
   * @return {module:model/Opzione} The populated <code>Opzione</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Opzione();
      if (data.hasOwnProperty('tipo'))
        obj.tipo = ApiClient.convertToType(data['tipo'], 'String');
      if (data.hasOwnProperty('prezzo'))
        obj.prezzo = ApiClient.convertToType(data['prezzo'], 'Number');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} tipo
 */
Opzione.prototype.tipo = undefined;

/**
 * @member {Number} prezzo
 */
Opzione.prototype.prezzo = undefined;

/**
 * @member {String} nome
 */
Opzione.prototype.nome = undefined;

