/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import JsonVisura from './JsonVisura';

/**
 * The PostBodyId model module.
 * @module model/PostBodyId
 * @version 2.0.0
 */
export default class PostBodyId {
  /**
   * Constructs a new <code>PostBodyId</code>.
   * @alias module:model/PostBodyId
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PostBodyId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostBodyId} obj Optional instance to populate.
   * @return {module:model/PostBodyId} The populated <code>PostBodyId</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostBodyId();
      if (data.hasOwnProperty('json_visura'))
        obj.jsonVisura = JsonVisura.constructFromObject(data['json_visura']);
    }
    return obj;
  }
}

/**
 * @member {module:model/JsonVisura} jsonVisura
 */
PostBodyId.prototype.jsonVisura = undefined;

