/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import JsonVisura from './JsonVisura';

/**
 * The PutBody model module.
 * @module model/PutBody
 * @version 2.0.0
 */
export default class PutBody {
  /**
   * Constructs a new <code>PutBody</code>.
   * @alias module:model/PutBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PutBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutBody} obj Optional instance to populate.
   * @return {module:model/PutBody} The populated <code>PutBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutBody();
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'Number');
      if (data.hasOwnProperty('json_visura'))
        obj.jsonVisura = JsonVisura.constructFromObject(data['json_visura']);
      if (data.hasOwnProperty('json_visura.$n'))
        obj.jsonVisuraN = ApiClient.convertToType(data['json_visura.$n'], 'String');
      if (data.hasOwnProperty('email_target'))
        obj.emailTarget = ApiClient.convertToType(data['email_target'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>state</code> property.
 * @enum {Number}
 * @readonly
 */
PutBody.StateEnum = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1
};
/**
 * Se la transazione è ancora aperta, con lo stato a 0, non verrà convalidata e passata al sistema fino a quando non verrà passato 1
 * @member {module:model/PutBody.StateEnum} state
 */
PutBody.prototype.state = undefined;

/**
 * @member {module:model/JsonVisura} jsonVisura
 */
PutBody.prototype.jsonVisura = undefined;

/**
 * Permette di modificare il singolo campo di input richiesto dal servizio
 * @member {String} jsonVisuraN
 */
PutBody.prototype.jsonVisuraN = undefined;

/**
 * Permette di ricevere il documento di servizio richiesto direttamente via e-mail una volta che il servizio è stato elaborato
 * @member {String} emailTarget
 */
PutBody.prototype.emailTarget = undefined;

