/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RicercaJsonMappato from './RicercaJsonMappato';

/**
 * The Ricerca model module.
 * @module model/Ricerca
 * @version 2.0.0
 */
export default class Ricerca {
  /**
   * Constructs a new <code>Ricerca</code>.
   * @alias module:model/Ricerca
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Ricerca</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ricerca} obj Optional instance to populate.
   * @return {module:model/Ricerca} The populated <code>Ricerca</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Ricerca();
      if (data.hasOwnProperty('id_ricerca'))
        obj.idRicerca = ApiClient.convertToType(data['id_ricerca'], 'String');
      if (data.hasOwnProperty('stato_ricerca'))
        obj.statoRicerca = ApiClient.convertToType(data['stato_ricerca'], 'String');
      if (data.hasOwnProperty('json_ricerca'))
        obj.jsonRicerca = ApiClient.convertToType(data['json_ricerca'], 'String');
      if (data.hasOwnProperty('json_mappato'))
        obj.jsonMappato = RicercaJsonMappato.constructFromObject(data['json_mappato']);
      if (data.hasOwnProperty('json_risultato'))
        obj.jsonRisultato = ApiClient.convertToType(data['json_risultato'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} idRicerca
 */
Ricerca.prototype.idRicerca = undefined;

/**
 * @member {String} statoRicerca
 */
Ricerca.prototype.statoRicerca = undefined;

/**
 * @member {String} jsonRicerca
 */
Ricerca.prototype.jsonRicerca = undefined;

/**
 * @member {module:model/RicercaJsonMappato} jsonMappato
 */
Ricerca.prototype.jsonMappato = undefined;

/**
 * @member {String} jsonRisultato
 */
Ricerca.prototype.jsonRisultato = undefined;

