/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RicercaJsonMappato model module.
 * @module model/RicercaJsonMappato
 * @version 2.0.0
 */
export default class RicercaJsonMappato {
  /**
   * Constructs a new <code>RicercaJsonMappato</code>.
   * @alias module:model/RicercaJsonMappato
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RicercaJsonMappato</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RicercaJsonMappato} obj Optional instance to populate.
   * @return {module:model/RicercaJsonMappato} The populated <code>RicercaJsonMappato</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RicercaJsonMappato();
      if (data.hasOwnProperty('field'))
        obj.field = ApiClient.convertToType(data['field'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} field
 */
RicercaJsonMappato.prototype.field = undefined;

