/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Richieste model module.
 * @module model/Richieste
 * @version 2.0.0
 */
export default class Richieste {
  /**
   * Constructs a new <code>Richieste</code>.
   * @alias module:model/Richieste
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Richieste</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Richieste} obj Optional instance to populate.
   * @return {module:model/Richieste} The populated <code>Richieste</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Richieste();
      if (data.hasOwnProperty('_id'))
        obj.id = ApiClient.convertToType(data['_id'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'Number');
      if (data.hasOwnProperty('hash_visura'))
        obj.hashVisura = ApiClient.convertToType(data['hash_visura'], 'String');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('ricerca'))
        obj.ricerca = ApiClient.convertToType(data['ricerca'], 'Boolean');
      if (data.hasOwnProperty('id_ricerca'))
        obj.idRicerca = ApiClient.convertToType(data['id_ricerca'], 'String');
      if (data.hasOwnProperty('prezzo_visura'))
        obj.prezzoVisura = ApiClient.convertToType(data['prezzo_visura'], 'Number');
      if (data.hasOwnProperty('prezzo_ricerca'))
        obj.prezzoRicerca = ApiClient.convertToType(data['prezzo_ricerca'], 'Number');
      if (data.hasOwnProperty('indice_ricerca'))
        obj.indiceRicerca = ApiClient.convertToType(data['indice_ricerca'], 'Number');
      if (data.hasOwnProperty('stato_richiesta'))
        obj.statoRichiesta = ApiClient.convertToType(data['stato_richiesta'], 'String');
      if (data.hasOwnProperty('email_target'))
        obj.emailTarget = ApiClient.convertToType(data['email_target'], 'String');
      if (data.hasOwnProperty('timestamp_creation'))
        obj.timestampCreation = ApiClient.convertToType(data['timestamp_creation'], 'Number');
      if (data.hasOwnProperty('timestamp_last_update'))
        obj.timestampLastUpdate = ApiClient.convertToType(data['timestamp_last_update'], 'Number');
      if (data.hasOwnProperty('owner'))
        obj.owner = ApiClient.convertToType(data['owner'], 'String');
      if (data.hasOwnProperty('sincrona'))
        obj.sincrona = ApiClient.convertToType(data['sincrona'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Richieste.prototype.id = undefined;

/**
 * @member {Number} state
 */
Richieste.prototype.state = undefined;

/**
 * @member {String} hashVisura
 */
Richieste.prototype.hashVisura = undefined;

/**
 * @member {String} nome
 */
Richieste.prototype.nome = undefined;

/**
 * @member {Boolean} ricerca
 */
Richieste.prototype.ricerca = undefined;

/**
 * @member {String} idRicerca
 */
Richieste.prototype.idRicerca = undefined;

/**
 * @member {Number} prezzoVisura
 */
Richieste.prototype.prezzoVisura = undefined;

/**
 * @member {Number} prezzoRicerca
 */
Richieste.prototype.prezzoRicerca = undefined;

/**
 * @member {Number} indiceRicerca
 */
Richieste.prototype.indiceRicerca = undefined;

/**
 * Allowed values for the <code>statoRichiesta</code> property.
 * @enum {String}
 * @readonly
 */
Richieste.StatoRichiestaEnum = {
  /**
   * value: "In ricerca"
   * @const
   */
  inRicerca: "In ricerca",

  /**
   * value: "In erogazione"
   * @const
   */
  inErogazione: "In erogazione",

  /**
   * value: "Dati disponibili"
   * @const
   */
  datiDisponibili: "Dati disponibili",

  /**
   * value: "Visura evasa"
   * @const
   */
  visuraEvasa: "Visura evasa",

  /**
   * value: "Annullata"
   * @const
   */
  annullata: "Annullata"
};
/**
 * @member {module:model/Richieste.StatoRichiestaEnum} statoRichiesta
 */
Richieste.prototype.statoRichiesta = undefined;

/**
 * @member {String} emailTarget
 */
Richieste.prototype.emailTarget = undefined;

/**
 * @member {Number} timestampCreation
 */
Richieste.prototype.timestampCreation = undefined;

/**
 * @member {Number} timestampLastUpdate
 */
Richieste.prototype.timestampLastUpdate = undefined;

/**
 * @member {String} owner
 */
Richieste.prototype.owner = undefined;

/**
 * @member {Boolean} sincrona
 */
Richieste.prototype.sincrona = undefined;

