/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CallbackData from './CallbackData';
import Esito from './Esito';
import Opzione from './Opzione';
import Ricerca from './Ricerca';
import TimestampStati from './TimestampStati';

/**
 * The Richiesta model module.
 * @module model/Richiesta
 * @version 2.0.0
 */
export default class Richiesta {
  /**
   * Constructs a new <code>Richiesta</code>.
   * @alias module:model/Richiesta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Richiesta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Richiesta} obj Optional instance to populate.
   * @return {module:model/Richiesta} The populated <code>Richiesta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Richiesta();
      if (data.hasOwnProperty('_id'))
        obj.id = ApiClient.convertToType(data['_id'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'Number');
      if (data.hasOwnProperty('hash_visura'))
        obj.hashVisura = ApiClient.convertToType(data['hash_visura'], 'String');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('callback'))
        obj.callback = ApiClient.convertToType(data['callback'], 'String');
      if (data.hasOwnProperty('ricerca'))
        obj.ricerca = ApiClient.convertToType(data['ricerca'], 'Boolean');
      if (data.hasOwnProperty('id_ricerca'))
        obj.idRicerca = ApiClient.convertToType(data['id_ricerca'], 'String');
      if (data.hasOwnProperty('prezzo_visura'))
        obj.prezzoVisura = ApiClient.convertToType(data['prezzo_visura'], 'Number');
      if (data.hasOwnProperty('prezzo_ricerca'))
        obj.prezzoRicerca = ApiClient.convertToType(data['prezzo_ricerca'], 'Number');
      if (data.hasOwnProperty('indice_ricerca'))
        obj.indiceRicerca = ApiClient.convertToType(data['indice_ricerca'], 'Number');
      if (data.hasOwnProperty('stato_richiesta'))
        obj.statoRichiesta = ApiClient.convertToType(data['stato_richiesta'], 'String');
      if (data.hasOwnProperty('email_target'))
        obj.emailTarget = ApiClient.convertToType(data['email_target'], 'String');
      if (data.hasOwnProperty('allegati'))
        obj.allegati = ApiClient.convertToType(data['allegati'], ['String']);
      if (data.hasOwnProperty('timestamp_creation'))
        obj.timestampCreation = ApiClient.convertToType(data['timestamp_creation'], 'Number');
      if (data.hasOwnProperty('timestamp_last_update'))
        obj.timestampLastUpdate = ApiClient.convertToType(data['timestamp_last_update'], 'Number');
      if (data.hasOwnProperty('timestamp_stati'))
        obj.timestampStati = TimestampStati.constructFromObject(data['timestamp_stati']);
      if (data.hasOwnProperty('callback_data'))
        obj.callbackData = CallbackData.constructFromObject(data['callback_data']);
      if (data.hasOwnProperty('opzioni'))
        obj.opzioni = ApiClient.convertToType(data['opzioni'], [Opzione]);
      if (data.hasOwnProperty('owner'))
        obj.owner = ApiClient.convertToType(data['owner'], 'String');
      if (data.hasOwnProperty('sincrona'))
        obj.sincrona = ApiClient.convertToType(data['sincrona'], 'Boolean');
      if (data.hasOwnProperty('ricerche'))
        obj.ricerche = ApiClient.convertToType(data['ricerche'], [Ricerca]);
      if (data.hasOwnProperty('esito'))
        obj.esito = Esito.constructFromObject(data['esito']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Richiesta.prototype.id = undefined;

/**
 * @member {Number} state
 */
Richiesta.prototype.state = undefined;

/**
 * @member {String} hashVisura
 */
Richiesta.prototype.hashVisura = undefined;

/**
 * @member {String} nome
 */
Richiesta.prototype.nome = undefined;

/**
 * @member {String} callback
 */
Richiesta.prototype.callback = undefined;

/**
 * @member {Boolean} ricerca
 */
Richiesta.prototype.ricerca = undefined;

/**
 * @member {String} idRicerca
 */
Richiesta.prototype.idRicerca = undefined;

/**
 * @member {Number} prezzoVisura
 */
Richiesta.prototype.prezzoVisura = undefined;

/**
 * @member {Number} prezzoRicerca
 */
Richiesta.prototype.prezzoRicerca = undefined;

/**
 * @member {Number} indiceRicerca
 */
Richiesta.prototype.indiceRicerca = undefined;

/**
 * Allowed values for the <code>statoRichiesta</code> property.
 * @enum {String}
 * @readonly
 */
Richiesta.StatoRichiestaEnum = {
  /**
   * value: "In ricerca"
   * @const
   */
  inRicerca: "In ricerca",

  /**
   * value: "In erogazione"
   * @const
   */
  inErogazione: "In erogazione",

  /**
   * value: "Dati disponibili"
   * @const
   */
  datiDisponibili: "Dati disponibili",

  /**
   * value: "Visura evasa"
   * @const
   */
  visuraEvasa: "Visura evasa",

  /**
   * value: "Annullata"
   * @const
   */
  annullata: "Annullata"
};
/**
 * @member {module:model/Richiesta.StatoRichiestaEnum} statoRichiesta
 */
Richiesta.prototype.statoRichiesta = undefined;

/**
 * @member {String} emailTarget
 */
Richiesta.prototype.emailTarget = undefined;

/**
 * @member {Array.<String>} allegati
 */
Richiesta.prototype.allegati = undefined;

/**
 * @member {Number} timestampCreation
 */
Richiesta.prototype.timestampCreation = undefined;

/**
 * @member {Number} timestampLastUpdate
 */
Richiesta.prototype.timestampLastUpdate = undefined;

/**
 * @member {module:model/TimestampStati} timestampStati
 */
Richiesta.prototype.timestampStati = undefined;

/**
 * @member {module:model/CallbackData} callbackData
 */
Richiesta.prototype.callbackData = undefined;

/**
 * @member {Array.<module:model/Opzione>} opzioni
 */
Richiesta.prototype.opzioni = undefined;

/**
 * @member {String} owner
 */
Richiesta.prototype.owner = undefined;

/**
 * @member {Boolean} sincrona
 */
Richiesta.prototype.sincrona = undefined;

/**
 * @member {Array.<module:model/Ricerca>} ricerche
 */
Richiesta.prototype.ricerche = undefined;

/**
 * @member {module:model/Esito} esito
 */
Richiesta.prototype.esito = undefined;

