/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TimestampStati model module.
 * @module model/TimestampStati
 * @version 2.0.0
 */
export default class TimestampStati {
  /**
   * Constructs a new <code>TimestampStati</code>.
   * @alias module:model/TimestampStati
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TimestampStati</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TimestampStati} obj Optional instance to populate.
   * @return {module:model/TimestampStati} The populated <code>TimestampStati</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TimestampStati();
      if (data.hasOwnProperty('in_ricerca'))
        obj.inRicerca = ApiClient.convertToType(data['in_ricerca'], 'Number');
      if (data.hasOwnProperty('in_erogazione'))
        obj.inErogazione = ApiClient.convertToType(data['in_erogazione'], 'Number');
      if (data.hasOwnProperty('dati_disponibili'))
        obj.datiDisponibili = ApiClient.convertToType(data['dati_disponibili'], 'Number');
      if (data.hasOwnProperty('visura_evasa'))
        obj.visuraEvasa = ApiClient.convertToType(data['visura_evasa'], 'Number');
      if (data.hasOwnProperty('annullata'))
        obj.annullata = ApiClient.convertToType(data['annullata'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} inRicerca
 */
TimestampStati.prototype.inRicerca = undefined;

/**
 * @member {Number} inErogazione
 */
TimestampStati.prototype.inErogazione = undefined;

/**
 * @member {Number} datiDisponibili
 */
TimestampStati.prototype.datiDisponibili = undefined;

/**
 * @member {Number} visuraEvasa
 */
TimestampStati.prototype.visuraEvasa = undefined;

/**
 * @member {Number} annullata
 */
TimestampStati.prototype.annullata = undefined;

