/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import JsonStruttura from './JsonStruttura';
import Opzione from './Opzione';

/**
 * The Visura model module.
 * @module model/Visura
 * @version 2.0.0
 */
export default class Visura {
  /**
   * Constructs a new <code>Visura</code>.
   * @alias module:model/Visura
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Visura</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Visura} obj Optional instance to populate.
   * @return {module:model/Visura} The populated <code>Visura</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Visura();
      if (data.hasOwnProperty('nome_visura'))
        obj.nomeVisura = ApiClient.convertToType(data['nome_visura'], 'String');
      if (data.hasOwnProperty('nome_categoria'))
        obj.nomeCategoria = ApiClient.convertToType(data['nome_categoria'], 'String');
      if (data.hasOwnProperty('json_struttura'))
        obj.jsonStruttura = JsonStruttura.constructFromObject(data['json_struttura']);
      if (data.hasOwnProperty('ricerca'))
        obj.ricerca = ApiClient.convertToType(data['ricerca'], 'Boolean');
      if (data.hasOwnProperty('prezzo_visura'))
        obj.prezzoVisura = ApiClient.convertToType(data['prezzo_visura'], 'Number');
      if (data.hasOwnProperty('prezzo_ricerca'))
        obj.prezzoRicerca = ApiClient.convertToType(data['prezzo_ricerca'], 'Number');
      if (data.hasOwnProperty('hash_visura'))
        obj.hashVisura = ApiClient.convertToType(data['hash_visura'], 'String');
      if (data.hasOwnProperty('opzioni'))
        obj.opzioni = ApiClient.convertToType(data['opzioni'], [Opzione]);
      if (data.hasOwnProperty('sincrona'))
        obj.sincrona = ApiClient.convertToType(data['sincrona'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} nomeVisura
 */
Visura.prototype.nomeVisura = undefined;

/**
 * @member {String} nomeCategoria
 */
Visura.prototype.nomeCategoria = undefined;

/**
 * @member {module:model/JsonStruttura} jsonStruttura
 */
Visura.prototype.jsonStruttura = undefined;

/**
 * @member {Boolean} ricerca
 */
Visura.prototype.ricerca = undefined;

/**
 * @member {Number} prezzoVisura
 */
Visura.prototype.prezzoVisura = undefined;

/**
 * @member {Number} prezzoRicerca
 */
Visura.prototype.prezzoRicerca = undefined;

/**
 * @member {String} hashVisura
 */
Visura.prototype.hashVisura = undefined;

/**
 * @member {Array.<module:model/Opzione>} opzioni
 */
Visura.prototype.opzioni = undefined;

/**
 * @member {Boolean} sincrona
 */
Visura.prototype.sincrona = undefined;

