/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Visure model module.
 * @module model/Visure
 * @version 2.0.0
 */
export default class Visure {
  /**
   * Constructs a new <code>Visure</code>.
   * @alias module:model/Visure
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Visure</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Visure} obj Optional instance to populate.
   * @return {module:model/Visure} The populated <code>Visure</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Visure();
      if (data.hasOwnProperty('nome_visura'))
        obj.nomeVisura = ApiClient.convertToType(data['nome_visura'], 'String');
      if (data.hasOwnProperty('nome_categoria'))
        obj.nomeCategoria = ApiClient.convertToType(data['nome_categoria'], 'String');
      if (data.hasOwnProperty('hash_visura'))
        obj.hashVisura = ApiClient.convertToType(data['hash_visura'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} nomeVisura
 */
Visure.prototype.nomeVisura = undefined;

/**
 * @member {String} nomeCategoria
 */
Visure.prototype.nomeCategoria = undefined;

/**
 * @member {String} hashVisura
 */
Visure.prototype.hashVisura = undefined;

