/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Visengine20);
  }
}(this, function(expect, Visengine20) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Dollaro', function() {
      beforeEach(function() {
        instance = new Visengine20.Dollaro();
      });

      it('should create an instance of Dollaro', function() {
        // TODO: update the code to test Dollaro
        expect(instance).to.be.a(Visengine20.Dollaro);
      });

      it('should have the property nome (base name: "nome")', function() {
        // TODO: update the code to test the property nome
        expect(instance).to.have.property('nome');
        // expect(instance.nome).to.be(expectedValueLiteral);
      });

      it('should have the property tipo (base name: "tipo")', function() {
        // TODO: update the code to test the property tipo
        expect(instance).to.have.property('tipo');
        // expect(instance.tipo).to.be(expectedValueLiteral);
      });

      it('should have the property opzioni (base name: "opzioni")', function() {
        // TODO: update the code to test the property opzioni
        expect(instance).to.have.property('opzioni');
        // expect(instance.opzioni).to.be(expectedValueLiteral);
      });

      it('should have the property ordine (base name: "ordine")', function() {
        // TODO: update the code to test the property ordine
        expect(instance).to.have.property('ordine');
        // expect(instance.ordine).to.be(expectedValueLiteral);
      });

      it('should have the property istruzioni (base name: "istruzioni")', function() {
        // TODO: update the code to test the property istruzioni
        expect(instance).to.have.property('istruzioni');
        // expect(instance.istruzioni).to.be(expectedValueLiteral);
      });

      it('should have the property _null (base name: "null")', function() {
        // TODO: update the code to test the property _null
        expect(instance).to.have.property('_null');
        // expect(instance._null).to.be(expectedValueLiteral);
      });

    });
  });

}));
