/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Visengine20);
  }
}(this, function(expect, Visengine20) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('JsonStruttura', function() {
      beforeEach(function() {
        instance = new Visengine20.JsonStruttura();
      });

      it('should create an instance of JsonStruttura', function() {
        // TODO: update the code to test JsonStruttura
        expect(instance).to.be.a(Visengine20.JsonStruttura);
      });

      it('should have the property campi (base name: "campi")', function() {
        // TODO: update the code to test the property campi
        expect(instance).to.have.property('campi');
        // expect(instance.campi).to.be(expectedValueLiteral);
      });

      it('should have the property validazione (base name: "validazione")', function() {
        // TODO: update the code to test the property validazione
        expect(instance).to.have.property('validazione');
        // expect(instance.validazione).to.be(expectedValueLiteral);
      });

      it('should have the property istruzioni (base name: "istruzioni")', function() {
        // TODO: update the code to test the property istruzioni
        expect(instance).to.have.property('istruzioni');
        // expect(instance.istruzioni).to.be(expectedValueLiteral);
      });

      it('should have the property istruzioniRicerca (base name: "istruzioni_ricerca")', function() {
        // TODO: update the code to test the property istruzioniRicerca
        expect(instance).to.have.property('istruzioniRicerca');
        // expect(instance.istruzioniRicerca).to.be(expectedValueLiteral);
      });

    });
  });

}));
