/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Visengine20);
  }
}(this, function(expect, Visengine20) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('JsonVisura', function() {
      beforeEach(function() {
        instance = new Visengine20.JsonVisura();
      });

      it('should create an instance of JsonVisura', function() {
        // TODO: update the code to test JsonVisura
        expect(instance).to.be.a(Visengine20.JsonVisura);
      });

      it('should have the property _0 (base name: "$0")', function() {
        // TODO: update the code to test the property _0
        expect(instance).to.have.property('_0');
        // expect(instance._0).to.be(expectedValueLiteral);
      });

      it('should have the property n (base name: "$n")', function() {
        // TODO: update the code to test the property n
        expect(instance).to.have.property('n');
        // expect(instance.n).to.be(expectedValueLiteral);
      });

    });
  });

}));
