/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Visengine20);
  }
}(this, function(expect, Visengine20) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PostBodyOpzioni', function() {
      beforeEach(function() {
        instance = new Visengine20.PostBodyOpzioni();
      });

      it('should create an instance of PostBodyOpzioni', function() {
        // TODO: update the code to test PostBodyOpzioni
        expect(instance).to.be.a(Visengine20.PostBodyOpzioni);
      });

      it('should have the property opzione0 (base name: "opzione_0")', function() {
        // TODO: update the code to test the property opzione0
        expect(instance).to.have.property('opzione0');
        // expect(instance.opzione0).to.be(expectedValueLiteral);
      });

      it('should have the property opzioneN (base name: "opzione_n")', function() {
        // TODO: update the code to test the property opzioneN
        expect(instance).to.have.property('opzioneN');
        // expect(instance.opzioneN).to.be(expectedValueLiteral);
      });

    });
  });

}));
