/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Visengine20);
  }
}(this, function(expect, Visengine20) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Ricerca', function() {
      beforeEach(function() {
        instance = new Visengine20.Ricerca();
      });

      it('should create an instance of Ricerca', function() {
        // TODO: update the code to test Ricerca
        expect(instance).to.be.a(Visengine20.Ricerca);
      });

      it('should have the property idRicerca (base name: "id_ricerca")', function() {
        // TODO: update the code to test the property idRicerca
        expect(instance).to.have.property('idRicerca');
        // expect(instance.idRicerca).to.be(expectedValueLiteral);
      });

      it('should have the property statoRicerca (base name: "stato_ricerca")', function() {
        // TODO: update the code to test the property statoRicerca
        expect(instance).to.have.property('statoRicerca');
        // expect(instance.statoRicerca).to.be(expectedValueLiteral);
      });

      it('should have the property jsonRicerca (base name: "json_ricerca")', function() {
        // TODO: update the code to test the property jsonRicerca
        expect(instance).to.have.property('jsonRicerca');
        // expect(instance.jsonRicerca).to.be(expectedValueLiteral);
      });

      it('should have the property jsonMappato (base name: "json_mappato")', function() {
        // TODO: update the code to test the property jsonMappato
        expect(instance).to.have.property('jsonMappato');
        // expect(instance.jsonMappato).to.be(expectedValueLiteral);
      });

      it('should have the property jsonRisultato (base name: "json_risultato")', function() {
        // TODO: update the code to test the property jsonRisultato
        expect(instance).to.have.property('jsonRisultato');
        // expect(instance.jsonRisultato).to.be(expectedValueLiteral);
      });

    });
  });

}));
