/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Visengine20);
  }
}(this, function(expect, Visengine20) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TimestampStati', function() {
      beforeEach(function() {
        instance = new Visengine20.TimestampStati();
      });

      it('should create an instance of TimestampStati', function() {
        // TODO: update the code to test TimestampStati
        expect(instance).to.be.a(Visengine20.TimestampStati);
      });

      it('should have the property inRicerca (base name: "in_ricerca")', function() {
        // TODO: update the code to test the property inRicerca
        expect(instance).to.have.property('inRicerca');
        // expect(instance.inRicerca).to.be(expectedValueLiteral);
      });

      it('should have the property inErogazione (base name: "in_erogazione")', function() {
        // TODO: update the code to test the property inErogazione
        expect(instance).to.have.property('inErogazione');
        // expect(instance.inErogazione).to.be(expectedValueLiteral);
      });

      it('should have the property datiDisponibili (base name: "dati_disponibili")', function() {
        // TODO: update the code to test the property datiDisponibili
        expect(instance).to.have.property('datiDisponibili');
        // expect(instance.datiDisponibili).to.be(expectedValueLiteral);
      });

      it('should have the property visuraEvasa (base name: "visura_evasa")', function() {
        // TODO: update the code to test the property visuraEvasa
        expect(instance).to.have.property('visuraEvasa');
        // expect(instance.visuraEvasa).to.be(expectedValueLiteral);
      });

      it('should have the property annullata (base name: "annullata")', function() {
        // TODO: update the code to test the property annullata
        expect(instance).to.have.property('annullata');
        // expect(instance.annullata).to.be(expectedValueLiteral);
      });

    });
  });

}));
