/*
 * Visengine 2.0
 * Questo servizio offre chiamate di rest per usufruire di tutta una serie di servizi camerali, catastali o di patronato legati a imprese e privati
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.59
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Allegato from './model/Allegato';
import CallbackData from './model/CallbackData';
import Campo from './model/Campo';
import Dollaro from './model/Dollaro';
import Esito from './model/Esito';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import JsonStruttura from './model/JsonStruttura';
import JsonVisura from './model/JsonVisura';
import Opzione from './model/Opzione';
import PostBody from './model/PostBody';
import PostBodyId from './model/PostBodyId';
import PostBodyOpzioni from './model/PostBodyOpzioni';
import PutBody from './model/PutBody';
import PutBodySearch from './model/PutBodySearch';
import Ricerca from './model/Ricerca';
import RicercaJsonMappato from './model/RicercaJsonMappato';
import Richiesta from './model/Richiesta';
import Richieste from './model/Richieste';
import TimestampStati from './model/TimestampStati';
import Visura from './model/Visura';
import Visure from './model/Visure';
import DocumentoApi from './api/DocumentoApi';
import RichiestaApi from './api/RichiestaApi';
import VisureApi from './api/VisureApi';

/**
* Questo_servizio_offre_chiamate_di_rest_per_usufruire_di_tutta_una_serie_di_servizi_camerali_catastali_o_di_patronato_legati_a_imprese_e_privati.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Visengine20 = require('index'); // See note below*.
* var xxxSvc = new Visengine20.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Visengine20.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Visengine20.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Visengine20.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Allegato model constructor.
     * @property {module:model/Allegato}
     */
    Allegato,

    /**
     * The CallbackData model constructor.
     * @property {module:model/CallbackData}
     */
    CallbackData,

    /**
     * The Campo model constructor.
     * @property {module:model/Campo}
     */
    Campo,

    /**
     * The Dollaro model constructor.
     * @property {module:model/Dollaro}
     */
    Dollaro,

    /**
     * The Esito model constructor.
     * @property {module:model/Esito}
     */
    Esito,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The JsonStruttura model constructor.
     * @property {module:model/JsonStruttura}
     */
    JsonStruttura,

    /**
     * The JsonVisura model constructor.
     * @property {module:model/JsonVisura}
     */
    JsonVisura,

    /**
     * The Opzione model constructor.
     * @property {module:model/Opzione}
     */
    Opzione,

    /**
     * The PostBody model constructor.
     * @property {module:model/PostBody}
     */
    PostBody,

    /**
     * The PostBodyId model constructor.
     * @property {module:model/PostBodyId}
     */
    PostBodyId,

    /**
     * The PostBodyOpzioni model constructor.
     * @property {module:model/PostBodyOpzioni}
     */
    PostBodyOpzioni,

    /**
     * The PutBody model constructor.
     * @property {module:model/PutBody}
     */
    PutBody,

    /**
     * The PutBodySearch model constructor.
     * @property {module:model/PutBodySearch}
     */
    PutBodySearch,

    /**
     * The Ricerca model constructor.
     * @property {module:model/Ricerca}
     */
    Ricerca,

    /**
     * The RicercaJsonMappato model constructor.
     * @property {module:model/RicercaJsonMappato}
     */
    RicercaJsonMappato,

    /**
     * The Richiesta model constructor.
     * @property {module:model/Richiesta}
     */
    Richiesta,

    /**
     * The Richieste model constructor.
     * @property {module:model/Richieste}
     */
    Richieste,

    /**
     * The TimestampStati model constructor.
     * @property {module:model/TimestampStati}
     */
    TimestampStati,

    /**
     * The Visura model constructor.
     * @property {module:model/Visura}
     */
    Visura,

    /**
     * The Visure model constructor.
     * @property {module:model/Visure}
     */
    Visure,

    /**
    * The DocumentoApi service constructor.
    * @property {module:api/DocumentoApi}
    */
    DocumentoApi,

    /**
    * The RichiestaApi service constructor.
    * @property {module:api/RichiestaApi}
    */
    RichiestaApi,

    /**
    * The VisureApi service constructor.
    * @property {module:api/VisureApi}
    */
    VisureApi
};
